#!/bin/bash
set -e

PACKAGES=""
DAEMONS=""

# Apt

## Custom sources

    if ! diff -q config/apt/sources.list /etc/apt/sources.list > /dev/null; then
      sudo cp config/apt/sources.list /etc/apt/sources.list
      sudo apt-get update -qq
    fi

## General

    function packages {
      for pkg in $1; do
        if ! dpkg -s $pkg > /dev/null; then
          sudo apt-get install -qqy $pkg
          $PACKAGES="$PACKAGES $pkg"
        fi
      done
    }

    packages "git vim"

## Used for my super awesome aac2ac3 script

    packages "aften faad mediainfo mkvtoolnix"

## Used for merging avi files

    packages "mencoder"

# Samba

    packages "samba"

    if ! diff -q config/samba/smb.conf /etc/samba/smb.conf > /dev/null; then
      sudo cp config/samba/smb.conf /etc/samba/smb.conf
      sudo service samba stop > /dev/null
      sudo service samba start > /dev/null
      $DAEMONS="$DAEMONS samba"
    fi

# Mail

    packages "exim4"

    if ! diff -q config/exim4/exim4.conf /etc/exim4/update-exim4.conf.conf > /dev/null; then
      sudo cp config/exim4/exim4.conf /etc/exim4/update-exim4.conf.conf
      sudo update-exim4.conf
      sudo service exim4 restart > /dev/null
      $DAEMONS="$DAEMONS exim4"
    fi

# Networking

## General

    NETWORKING_CHANGED="0"

    if ! diff -q config/network/hosts /etc/hosts > /dev/null; then
      sudo cp config/network/hosts /etc/hosts
      $NETWORKING_CHANGED="1"
    fi

    if ! diff -q config/network/resolv.conf /etc/resolv.conf > /dev/null; then
      sudo cp config/network/resolv.conf /etc/resolv.conf
      $NETWORKING_CHANGED="1"
    fi

    if ! diff -q config/network/interfaces /etc/network/interfaces > /dev/null; then
      sudo cp config/network/interfaces /etc/network/interfaces
      $NETWORKING_CHANGED="1"
    fi

    if [ "x${NETWORKING_CHANGED}" == "x1" ]; then
      sudo service networking restart > /dev/null
      $DAEMONS="$DAEMONS networking"
    fi

## DNS

    DNS_CHANGED="0"

    packages "bind9"

    for file in "named.conf.local named.conf.options zone.home.tigris.id.au zone.1.168.192.in-addr.arpa"; do
      if ! diff -q config/dns/${file} /etc/bind/${file} > /dev/null; then
        sudo cp config/dns/${file} /etc/bind/${file}
        $DNS_CHANGED="1"
      fi
    done

    if [ "x${DNS_CHANGED}" == "x1" ]; then
      sudo service bind9 restart > /dev/null
      $DAEMONS="$DAEMONS bind9"
    fi

## DHCP

    packages "isc-dhcp-server"

    if ! diff -q config/dhcp/default.conf /etc/default/isc-dhcp-server > /dev/null; then
      sudo cp config/dhcp/default.conf /etc/default/isc-dhcp-server
    fi

    if ! diff -q config/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf > /dev/null; then
      sudo cp config/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf
      sudo service isc-dhcp-server restart > /dev/null
      $DAEMONS="$DAEMONS isc-dhcp-server"
    fi

echo -e "The following packages (and dependencies) were installed:\n    ${PACKAGES:-none}"
echo -e "The following daemons were restarted (or stopped and started):\n    ${DAEMONS:-none}"

exit 0
