#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

PACKAGES=""
DAEMONS=""

# Apt

## Custom sources

    gpg --keyserver pgpkeys.mit.edu --recv-key 07DC563D1F41B907 >/dev/null 2>/dev/null
    gpg -a --export 07DC563D1F41B907 | sudo apt-key add - >/dev/null

    if ! diff -q config/apt/sources.list /etc/apt/sources.list >/dev/null 2>/dev/null; then
      sudo cp config/apt/sources.list /etc/apt/sources.list
      sudo -E apt-get update -qq
    fi

## General

    function packages {
      for pkg in $1; do
        if ! dpkg -s $pkg >/dev/null 2>/dev/null; then
          sudo -E apt-get install -qqy $pkg > /dev/null
          PACKAGES="${PACKAGES}${pkg} "
        fi
      done
    }

    packages "git vim smartmontools ack-grep command-not-found mdadm hddtemp xfsprogs parted screen"

## Used for my super awesome aac2ac3 script

    packages "aften faad mediainfo mkvtoolnix"

## Used for merging avi files

    packages "mencoder"

## Needed for backup scripts etc

    packages "cifs-utils"

# Cron

    if ! diff -q config/cron/home_tigris_id_au /etc/cron.d/home_tigris_id_au >/dev/null 2>/dev/null; then
      sudo cp config/cron/home_tigris_id_au /etc/cron.d/home_tigris_id_au
      sudo service cron reload > /dev/null
      DAEMONS="${DAEMONS}cron "
    fi

# Samba

    packages "samba"

    if ! diff -q config/samba/smb.conf /etc/samba/smb.conf >/dev/null 2>/dev/null; then
      sudo cp config/samba/smb.conf /etc/samba/smb.conf
      # Samba is stop/start because restart doesn't seem to go down well
      sudo service samba stop > /dev/null
      sudo service samba start > /dev/null
      DAEMONS="${DAEMONS}samba "
    fi

# Mail

    packages "exim4"

    if ! diff -q config/exim4/exim4.conf /etc/exim4/update-exim4.conf.conf >/dev/null 2>/dev/null; then
      sudo cp config/exim4/exim4.conf /etc/exim4/update-exim4.conf.conf
      sudo update-exim4.conf
      sudo service exim4 restart > /dev/null
      DAEMONS="${DAEMONS}exim4 "
    fi

    if ! diff -q config/exim4/aliases /etc/aliases >/dev/null 2>/dev/null; then
      sudo cp config/exim4/aliases /etc/aliases
      sudo newaliases
      sudo service exim4 restart > /dev/null
      DAEMONS="${DAEMONS}exim4 "
    fi

# Networking

## General

    NETWORKING_CHANGED="0"

    if ! diff -q config/network/hosts /etc/hosts >/dev/null 2>/dev/null; then
      sudo cp config/network/hosts /etc/hosts
      NETWORKING_CHANGED="1"
    fi

    if ! diff -q config/network/interfaces /etc/network/interfaces >/dev/null 2>/dev/null; then
      sudo cp config/network/interfaces /etc/network/interfaces
      NETWORKING_CHANGED="1"
    fi

    if [ "x${NETWORKING_CHANGED}" == "x1" ]; then
      # Networking restarts are pretty flakey :/
      sudo service networking stop > /dev/null
      sleep 2
      sudo service networking start > /dev/null
      DAEMONS="${DAEMONS}networking "
    fi

## DNS

    DNS_CHANGED="0"

    packages "bind9"

    for file in named.conf.local named.conf.options zone.home.tigris.id.au zone.1.168.192.in-addr.arpa; do
      if ! diff -q config/dns/${file} /etc/bind/${file} >/dev/null 2>/dev/null; then
        sudo cp config/dns/${file} /etc/bind/${file}
        DNS_CHANGED="1"
      fi
    done

    if [ "x${DNS_CHANGED}" == "x1" ]; then
      sudo service bind9 restart > /dev/null
      DAEMONS="${DAEMONS}bind9 "
    fi

## DHCP

    packages "isc-dhcp-server"

    if ! diff -q config/dhcp/default.conf /etc/default/isc-dhcp-server >/dev/null 2>/dev/null; then
      sudo cp config/dhcp/default.conf /etc/default/isc-dhcp-server
    fi

    if ! diff -q config/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf >/dev/null 2>/dev/null; then
      sudo cp config/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf
      sudo service isc-dhcp-server restart > /dev/null
      DAEMONS="${DAEMONS}isc-dhcp-server "
    fi

## Dynamic DNS

    DDNS_CHANGED="0"

    # These 2 files are installed before ddclient installs because it complains
    # and wants to be interactive otherwise.
    if ! sudo diff -q config/ddclient/default.conf /etc/default/ddclient >/dev/null 2>/dev/null; then
      sudo cp config/ddclient/default.conf /etc/default/ddclient
    fi

    # Create temp copy of ddclient.conf with password in it
    sudo cp config/ddclient/ddclient.conf ~root/.tmp.ddclient.conf
    sudo chmod 0600 ~root/.tmp.ddclient.conf
    sudo sed -i -e "s/__PASSWORD__/$(sudo cat ~root/.ddclient)/" ~root/.tmp.ddclient.conf

    if ! sudo diff -q ~root/.tmp.ddclient.conf /etc/ddclient.conf >/dev/null 2>/dev/null; then
      sudo cp ~root/.tmp.ddclient.conf /etc/ddclient.conf
      DDNS_CHANGED="1"
    fi

    packages "ddclient"

    if [ "x${DDNS_CHANGED}" == "x1" ]; then
      sudo service ddclient restart > /dev/null
      DAEMONS="${DAEMONS}ddclient "
    fi

# Auto Deploy

    ln -sf /srv/home.tigris.id.au/config/hooks/post-merge /srv/home.tigris.id.au/.git/hooks/post-merge

# Finish up

    sudo update-command-not-found >/dev/null

    echo -e "The following packages (and dependencies) were installed:\n    ${PACKAGES:-none}"
    echo -e "The following daemons were restarted (or stopped and started):\n    ${DAEMONS:-none}"

    exit 0

